export const zh = String.raw`
    <section id="solutions" class="main-section solutions" data-section="solutions" aria-labelledby="solutions-title">
      <div class="shell reveal">
        <p class="eyebrow">CUSTOMER OUTCOMES</p>
        <h2 id="solutions-title" data-en="Start with the problem. Build an operable answer.">從問題出發，串成可維運的答案</h2>
        <div class="solution-layout">
          <div class="solution-rail" role="tablist" aria-label="客戶解決方案" data-label-en="Customer solutions">
            <button class="solution-card solution-card-1" id="solution-tab-0" role="tab" aria-selected="true" aria-controls="solution-panel" tabindex="0" data-solution="0"><span class="solution-number">01</span><span class="solution-icon" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i></span><b data-en="Build a stable IT foundation">建立穩定的 IT 基礎</b><small><strong data-en="Problem">問題</strong><span data-en="Devices and backups lack a shared baseline">設備與備份缺乏共同基線</span></small><small><strong data-en="Elias Net assists">協助</strong><span data-en="Map architecture, breakpoints and recovery paths">整理架構、斷點與回復路徑</span></small><em data-en="MAINTAINABLE FOUNDATION">成果 · 可維護基礎</em></button>
            <button class="solution-card solution-card-2" id="solution-tab-1" role="tab" aria-selected="false" aria-controls="solution-panel" tabindex="-1" data-solution="1"><span class="solution-number">02</span><span class="solution-icon" aria-hidden="true"><i></i><i></i><i></i></span><b data-en="Connect scattered systems">串起分散的系統與服務</b><small><strong data-en="Problem">問題</strong><span data-en="Identities, cloud and suppliers operate apart">帳號、雲端與供應商各自運作</span></small><small><strong data-en="Elias Net assists">協助</strong><span data-en="Define service relationships and access boundaries">建立服務關係及權限邊界</span></small><em data-en="CLEAR OWNERSHIP">成果 · 清楚責任界線</em></button>
            <button class="solution-card solution-card-3" id="solution-tab-2" role="tab" aria-selected="false" aria-controls="solution-panel" tabindex="-1" data-solution="2"><span class="solution-number">03</span><span class="solution-icon" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i></span><b data-en="Make security events clear">讓資安事件更容易理解</b><small><strong data-en="Problem">問題</strong><span data-en="Alerts repeat without event context">告警重複且缺乏事件脈絡</span></small><small><strong data-en="Elias Net assists">協助</strong><span data-en="Correlate assets, services and time">依資產、服務與時間進行關聯</span></small><em data-en="EVENT PRIORITY">成果 · 事件優先順序</em></button>
            <button class="solution-card solution-card-4" id="solution-tab-3" role="tab" aria-selected="false" aria-controls="solution-panel" tabindex="-1" data-solution="3"><span class="solution-number">04</span><span class="solution-icon" aria-hidden="true"><i></i><i></i><i></i><i></i></span><b data-en="Reduce repetitive operations">降低重複維運工作</b><small><strong data-en="Problem">問題</strong><span data-en="Routine work depends on personal habits">例行作業依賴個人習慣</span></small><small><strong data-en="Elias Net assists">協助</strong><span data-en="Define steps, approvals and records">建立有步驟、有核准、有紀錄的流程</span></small><em data-en="STANDARD OPERATIONS">成果 · 標準化維運</em></button>
            <button class="solution-card solution-card-5" id="solution-tab-4" role="tab" aria-selected="false" aria-controls="solution-panel" tabindex="-1" data-solution="4"><span class="solution-number">05</span><span class="solution-icon" aria-hidden="true"><i></i><i></i></span><b data-en="Support night and holiday duty">協助夜間與假日值班</b><small><strong data-en="Problem">問題</strong><span data-en="Off-hours events lack immediate context">非上班時段缺乏即時事件脈絡</span></small><small><strong data-en="Elias Net assists">協助</strong><span data-en="Organize anomaly, impact and priority">整理異常、影響與處理優先順序</span></small><em data-en="CLEAR ON-CALL NOTICE">成果 · 清楚值班通知</em></button>
            <button class="solution-card solution-card-6" id="solution-tab-5" role="tab" aria-selected="false" aria-controls="solution-panel" tabindex="-1" data-solution="5"><span class="solution-number">06</span><span class="solution-icon" aria-hidden="true"><i></i><i></i><i></i></span><b data-en="Keep critical actions human-led">重要操作保留人員決定</b><small><strong data-en="Problem">問題</strong><span data-en="High-impact actions lack clear approval">高影響操作缺乏清楚核准</span></small><small><strong data-en="Elias Net assists">協助</strong><span data-en="Stop before execution and show target, reason and risk">執行前停止並顯示目標、原因及風險</span></small><em data-en="HUMAN REVIEW REQUIRED">成果 · 人員確認後執行</em></button>
            <button class="solution-card solution-card-7" id="solution-tab-6" role="tab" aria-selected="false" aria-controls="solution-panel" tabindex="-1" data-solution="6"><span class="solution-number">07</span><span class="solution-icon" aria-hidden="true"><i></i><i></i><i></i><i></i></span><b data-en="Turn experience into team knowledge">將處理經驗轉成團隊知識</b><small><strong data-en="Problem">問題</strong><span data-en="Critical experience stays with a few people">重要經驗集中在少數人員</span></small><small><strong data-en="Elias Net assists">協助</strong><span data-en="Turn events, decisions and outcomes into searchable records">把事件、判斷與結果轉成可查詢紀錄</span></small><em data-en="KNOWLEDGE CONTINUITY">成果 · 知識可延續</em></button>
          </div>
          <article id="solution-panel" class="solution-panel" role="tabpanel" aria-labelledby="solution-tab-0" data-solution-panel>
            <span class="solution-index">SOLUTION 01</span>
            <h3 data-solution-title>建立穩定的 IT 基礎</h3>
            <dl><div><dt data-en="Problem">問題</dt><dd data-solution-problem>環境、備份與容災現況缺少共同基線。</dd></div><div><dt data-en="Integration">整合方式</dt><dd data-solution-method>盤點資產與關係，找出斷點與改善順序。</dd></div><div><dt data-en="Outcome">交付成果</dt><dd data-solution-outcome>架構圖、風險清單與分階段改善路徑。</dd></div><div><dt data-en="Best fit">適合情境</dt><dd data-solution-fit>準備汰換、擴充或重新整理既有環境的企業。</dd></div></dl>
            <div class="coverage"><span data-en="AI collaboration coverage (planning assessment)">AI 協作覆蓋度（規劃評估）</span><strong data-en="Workflow assessment pending">待流程盤點</strong><button type="button" data-method-open data-en="View calculation method">查看計算方式</button></div>
          </article>
        </div>
      </div>
    </section>
`;

export const en = String.raw`
    <section id="solutions" class="main-section solutions" data-section="solutions" aria-labelledby="solutions-title">
      <div class="shell reveal">
        <p class="eyebrow">CUSTOMER OUTCOMES</p>
        <h2 id="solutions-title" data-en="Start with the problem. Build an operable answer.">Start with the problem. Build an operable answer.</h2>
        <div class="solution-layout">
          <div class="solution-rail" role="tablist" aria-label="Customer solutions" data-label-en="Customer solutions">
            <button class="solution-card solution-card-1" id="solution-tab-0" role="tab" aria-selected="true" aria-controls="solution-panel" tabindex="0" data-solution="0"><span class="solution-number">01</span><span class="solution-icon" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i></span><b data-en="Build a stable IT foundation">Build a stable IT foundation</b><small><strong data-en="Problem">Problem</strong><span data-en="Devices and backups lack a shared baseline">Devices and backups lack a shared baseline</span></small><small><strong data-en="Elias Net assists">Elias Net assists</strong><span data-en="Map architecture, breakpoints and recovery paths">Map architecture, breakpoints and recovery paths</span></small><em data-en="MAINTAINABLE FOUNDATION">MAINTAINABLE FOUNDATION</em></button>
            <button class="solution-card solution-card-2" id="solution-tab-1" role="tab" aria-selected="false" aria-controls="solution-panel" tabindex="-1" data-solution="1"><span class="solution-number">02</span><span class="solution-icon" aria-hidden="true"><i></i><i></i><i></i></span><b data-en="Connect scattered systems">Connect scattered systems</b><small><strong data-en="Problem">Problem</strong><span data-en="Identities, cloud and suppliers operate apart">Identities, cloud and suppliers operate apart</span></small><small><strong data-en="Elias Net assists">Elias Net assists</strong><span data-en="Define service relationships and access boundaries">Define service relationships and access boundaries</span></small><em data-en="CLEAR OWNERSHIP">CLEAR OWNERSHIP</em></button>
            <button class="solution-card solution-card-3" id="solution-tab-2" role="tab" aria-selected="false" aria-controls="solution-panel" tabindex="-1" data-solution="2"><span class="solution-number">03</span><span class="solution-icon" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i></span><b data-en="Make security events clear">Make security events clear</b><small><strong data-en="Problem">Problem</strong><span data-en="Alerts repeat without event context">Alerts repeat without event context</span></small><small><strong data-en="Elias Net assists">Elias Net assists</strong><span data-en="Correlate assets, services and time">Correlate assets, services and time</span></small><em data-en="EVENT PRIORITY">EVENT PRIORITY</em></button>
            <button class="solution-card solution-card-4" id="solution-tab-3" role="tab" aria-selected="false" aria-controls="solution-panel" tabindex="-1" data-solution="3"><span class="solution-number">04</span><span class="solution-icon" aria-hidden="true"><i></i><i></i><i></i><i></i></span><b data-en="Reduce repetitive operations">Reduce repetitive operations</b><small><strong data-en="Problem">Problem</strong><span data-en="Routine work depends on personal habits">Routine work depends on personal habits</span></small><small><strong data-en="Elias Net assists">Elias Net assists</strong><span data-en="Define steps, approvals and records">Define steps, approvals and records</span></small><em data-en="STANDARD OPERATIONS">STANDARD OPERATIONS</em></button>
            <button class="solution-card solution-card-5" id="solution-tab-4" role="tab" aria-selected="false" aria-controls="solution-panel" tabindex="-1" data-solution="4"><span class="solution-number">05</span><span class="solution-icon" aria-hidden="true"><i></i><i></i></span><b data-en="Support night and holiday duty">Support night and holiday duty</b><small><strong data-en="Problem">Problem</strong><span data-en="Off-hours events lack immediate context">Off-hours events lack immediate context</span></small><small><strong data-en="Elias Net assists">Elias Net assists</strong><span data-en="Organize anomaly, impact and priority">Organize anomaly, impact and priority</span></small><em data-en="CLEAR ON-CALL NOTICE">CLEAR ON-CALL NOTICE</em></button>
            <button class="solution-card solution-card-6" id="solution-tab-5" role="tab" aria-selected="false" aria-controls="solution-panel" tabindex="-1" data-solution="5"><span class="solution-number">06</span><span class="solution-icon" aria-hidden="true"><i></i><i></i><i></i></span><b data-en="Keep critical actions human-led">Keep critical actions human-led</b><small><strong data-en="Problem">Problem</strong><span data-en="High-impact actions lack clear approval">High-impact actions lack clear approval</span></small><small><strong data-en="Elias Net assists">Elias Net assists</strong><span data-en="Stop before execution and show target, reason and risk">Stop before execution and show target, reason and risk</span></small><em data-en="HUMAN REVIEW REQUIRED">HUMAN REVIEW REQUIRED</em></button>
            <button class="solution-card solution-card-7" id="solution-tab-6" role="tab" aria-selected="false" aria-controls="solution-panel" tabindex="-1" data-solution="6"><span class="solution-number">07</span><span class="solution-icon" aria-hidden="true"><i></i><i></i><i></i><i></i></span><b data-en="Turn experience into team knowledge">Turn experience into team knowledge</b><small><strong data-en="Problem">Problem</strong><span data-en="Critical experience stays with a few people">Critical experience stays with a few people</span></small><small><strong data-en="Elias Net assists">Elias Net assists</strong><span data-en="Turn events, decisions and outcomes into searchable records">Turn events, decisions and outcomes into searchable records</span></small><em data-en="KNOWLEDGE CONTINUITY">KNOWLEDGE CONTINUITY</em></button>
          </div>
          <article id="solution-panel" class="solution-panel" role="tabpanel" aria-labelledby="solution-tab-0" data-solution-panel>
            <span class="solution-index">SOLUTION 01</span>
            <h3 data-solution-title>Build a stable IT foundation</h3>
            <dl><div><dt data-en="Problem">Problem</dt><dd data-solution-problem>The environment, backups and recovery plans lack a shared baseline.</dd></div><div><dt data-en="Integration">Integration</dt><dd data-solution-method>Map assets and relationships, then identify breakpoints and priorities.</dd></div><div><dt data-en="Outcome">Outcome</dt><dd data-solution-outcome>An architecture map, risk list and phased improvement path.</dd></div><div><dt data-en="Best fit">Best fit</dt><dd data-solution-fit>Organizations preparing to replace, expand or reorganize existing infrastructure.</dd></div></dl>
            <div class="coverage"><span data-en="AI collaboration coverage (planning assessment)">AI collaboration coverage (planning assessment)</span><strong data-en="Workflow assessment pending">Workflow assessment pending</strong><button type="button" data-method-open data-en="View calculation method">View calculation method</button></div>
          </article>
        </div>
      </div>
    </section>
`;
