(() => {
  'use strict';
  document.documentElement.classList.remove('no-js');
  const root = document.documentElement;
  const shell = document.querySelector('#worldShell');
  const scenes = new Map([...document.querySelectorAll('.scene')].map((scene) => [scene.id, scene]));
  const reducedQuery = matchMedia('(prefers-reduced-motion: reduce)');
  const storage = {
    get(key, fallback, allowed) { try { const value = localStorage.getItem(key); return allowed.includes(value) ? value : fallback; } catch (_) { return fallback; } },
    number(key, fallback, min, max) { try { const raw = localStorage.getItem(key); if (raw === null) return fallback; const value = Number(raw); return Number.isFinite(value) && value >= min && value <= max ? value : fallback; } catch (_) { return fallback; } },
    boolean(key, fallback) { try { const value = localStorage.getItem(key); return value === 'true' ? true : value === 'false' ? false : fallback; } catch (_) { return fallback; } },
    set(key, value) { try { localStorage.setItem(key, value); } catch (_) {} }
  };
  const state = {
    currentScene: 'entrance', previousScene: null, selectedRegion: null, visitedRegions: new Set(),
    effectPreference: storage.get('blockops:v3:effect-level', 'standard', ['static','standard','rich']),
    worldPhase: storage.get('blockops:v3:manual-phase', 'day', ['day','night']), reducedMotion: reducedQuery.matches,
    mission: { id: null, stage: 'idle', playback: 'stopped', approvedByMIS: false, actualAction: 0 },
    sound: { enabled: false, initialized: false, armed: false, muted: storage.boolean('blockops:v3:audio-muted', false), volume: storage.number('blockops:v3:audio-volume', .2, 0, 1) }
  };
  class TimerScope {
    constructor() { this.ids = new Set(); }
    timeout(callback, delay) { const id = window.setTimeout(() => { this.ids.delete(id); callback(); }, delay); this.ids.add(id); return id; }
    cancelAll() { this.ids.forEach(clearTimeout); this.ids.clear(); }
  }
  const globalTimers = new TimerScope();
  const sceneTimers = new TimerScope();
  const regionNames = { monitor:'監控高塔', ai:'AI 核心城', mask:'匿名化閘門', readonly:'唯讀資料礦坑', night:'夜間通知站', approval:'人工核准堡壘' };
  const stage = (id,label,title,facts) => [id,label,title,facts];
  const missionData = {
    monitor:{code:'MISSION 01',title:'監控高塔',theme:'#35ddd0',type:'monitor',action:'執行模擬檢查',stages:[stage('situation','SITUATION','一個設備節點由綠色轉為黃色。',['三個虛構節點集中顯示','掃描塔發現狀態偏移','不顯示真實主機名稱或 IP']),stage('assisting','BLOCKOPS ASSIST','唯讀掃描整理出匿名化的事件摘要。',['HOST-DEMO-03','Service State: Unexpected Stop','Risk: Medium · 建議先檢查近期事件']),stage('awaiting_mis','MIS DECISION','AI 提供判讀與檢查建議，流程停在 MIS 人工確認。',['不自行重啟服務','不執行 Shell 或 SSH','由 MIS 決定是否進入模擬檢查'])]},
    ai:{code:'MISSION 02',title:'AI 核心城',theme:'#8a63f6',type:'ai',action:'確認 AI 建議',stages:[stage('situation','SITUATION','多個告警方塊抵達 AI 核心。',['一般、注意、重要三類','只整理虛構事件','不取代 MIS']),stage('assisting','BLOCKOPS ASSIST','本機 AI 整理可能原因與下一步檢查建議。',['判讀影響範圍','提出檢查順序','不自行執行高風險操作']),stage('awaiting_mis','MIS DECISION','建議停在核准節點，由 MIS 決定下一步。',['Pilot 展示','最終由 MIS 確認','Actual Action 保持 0'])]},
    mask:{code:'MISSION 03',title:'匿名化閘門',theme:'#62c95a',type:'mask',action:'確認匿名結果',stages:[stage('situation','SITUATION','模擬事件攜帶 Host、User 與 Network 欄位抵達閘門。',['資料僅為虛構展示','敏感欄位不應直接進入通知','原始值不在畫面展開']),stage('assisting','BLOCKOPS ASSIST','同一顆資料方塊穿越遮罩光幕，保留判讀脈絡。',['HOST-01','USER-A','NET-X · 原始資料未送入公開服務']),stage('awaiting_mis','MIS DECISION','匿名結果停在出口，等待 MIS 確認資訊是否足以判讀。',['唯讀與匿名化先行','不傳送真實資料','確認後只完成動畫示範'])]},
    readonly:{code:'MISSION 04',title:'唯讀資料礦坑',theme:'#45b8f3',type:'readonly',action:'確認查詢範圍',stages:[stage('situation','SITUATION','查詢需求抵達單向資料軌。',['只用虛構事件','最多五筆展示資料','寫入箭頭封鎖']),stage('assisting','BLOCKOPS ASSIST','Gateway 檢查核准範圍與筆數。',['唯讀查詢','限制資料量','不修改 Wazuh 或帳號']),stage('awaiting_mis','MIS DECISION','結果停在出口，等待人工確認用途。',['不執行寫入','不控制防火牆','保留稽核概念'])]},
    night:{code:'MISSION 05',title:'夜間通知站',theme:'#ff635f',type:'night',action:'確認值班通知',stages:[stage('situation','SITUATION','夜間事件方塊抵達掃描塔。',['抽象異常單位','不呈現暴力','不使用官方角色']),stage('assisting','BLOCKOPS ASSIST','事件經分類與匿名化後送往抽象通知站。',['降低通知干擾','Google Chat／Telegram 僅為概念','未發送網路 Request']),stage('awaiting_mis','MIS DECISION','值班摘要等待 MIS 人工確認。',['ON-CALL MONITORING','不自動處置','人工確認燈號'])]},
    approval:{code:'MISSION 06',title:'人工核准堡壘',theme:'#f6c84c',type:'approval',action:'執行模擬核准',stages:[stage('situation','SITUATION','AI 建議抵達鎖定閘門。',['建議不是命令','目標與原因需清楚','正式能力維持唯讀']),stage('assisting','BLOCKOPS ASSIST','堡壘整理核准需要的目標、原因與限制。',['不執行 Restart','不執行 Firewall Action','保留結果紀錄概念']),stage('awaiting_mis','MIS DECISION','只有 MIS 可讓展示流程繼續。',['人是最終控制者','未來才可能受控處置','本輪仍為 simulate_only'])]}
  };
  const technologyData = [
    ['Qwen Local AI','離線驗證','在本機協助整理告警脈絡。','判讀摘要與檢查建議。','不自行執行操作。'],['Ollama Runtime','Pilot','提供本機模型的執行環境。','讓原型可在受控環境驗證。','不連接本網站展示。'],['Wazuh Read-only','唯讀','只允許核准範圍的事件查詢。','降低 AI 直接碰觸正式系統的風險。','禁止寫入、修改與刪除。'],['Anonymization Gateway','Pilot','在資料進入 AI 前遮蔽欄位。','保留判讀能力並減少敏感資訊暴露。','不保存原始資料。'],['Google Chat','未來規劃','將摘要轉為容易閱讀的通知。','協助值班人員快速掌握事件類型。','此網站不發送真實訊息。'],['Telegram','未來規劃','提供另一個抽象通知出口。','讓通知渠道可依治理規則選擇。','此網站沒有 Bot Token。'],['Hash Integrity','已驗證','用雜湊確認檔案是否一致。','協助辨識未預期的變更。','不等同惡意內容判定。'],['TLS Certificate','Pilot','保護服務之間的傳輸通道。','降低傳輸內容被攔截的風險。','仍需憑證生命週期管理。'],['Audit Log','未來規劃','記錄建議、核准與結果。','讓處置流程可追溯。','不得記錄密碼或 Token。'],['Human Approval','已驗證','讓 MIS 保留最終決策權。','阻止 AI 越過治理邊界。','任何高風險動作都不得自動通過。']
  ];
  const $ = (s) => document.querySelector(s); const $$ = (s) => [...document.querySelectorAll(s)];
  const effectiveEffect = () => state.reducedMotion ? 'static' : state.effectPreference;
  function renderEnvironment(){root.dataset.effects=effectiveEffect();root.dataset.phase=state.worldPhase;$('#entranceEffects').value=state.effectPreference;$('#hudEffects').value=state.effectPreference;const phase=state.worldPhase.toUpperCase();$('#entrancePhase').textContent=phase;$('#hudPhase').textContent=phase}
  function updateClock(){const d=new Date();const value=`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;$('#entranceClock').textContent=value;$('#hudClock').textContent=value}
  function scheduleClock(){updateClock();if(!document.hidden)globalTimers.timeout(scheduleClock,60000-new Date().getSeconds()*1000)}
  function updateHud(region=null){$('#hudRegion').textContent=region?regionNames[region]:state.currentScene==='world-map'?'世界地圖':scenes.get(state.currentScene)?.dataset.sceneName||'BLOCKOPS';$('#hudMission').textContent=state.currentScene==='mission'?missionData[state.mission.id].title:'探索世界';$('#hudStage').textContent=state.currentScene==='mission'?state.mission.stage.toUpperCase():'READY';$$('.region-bar button').forEach(b=>b.classList.toggle('is-active',b.dataset.shortcut===region))}
  function clearTransition(){const t=$('#worldTransition');t.classList.remove('is-active');t.setAttribute('aria-hidden','true');$('#entrance').removeAttribute('data-entrance-stage')}
  function showScene(id,options={}){const next=scenes.get(id);if(!next)return;sceneTimers.cancelAll();clearTransition();const current=scenes.get(state.currentScene);state.previousScene=state.currentScene;state.currentScene=id;current?.classList.remove('is-active');current?.setAttribute('hidden','');current?.setAttribute('data-scene-active','false');next.hidden=false;next.classList.add('is-active');next.setAttribute('data-scene-active','true');shell.dataset.scene=id;$('#worldHud').hidden=id==='entrance';updateHud(state.selectedRegion);if(options.focus!==false){const h=next.querySelector('h1,h2');(h||next).tabIndex=-1;(h||next).focus({preventScroll:true})}}
  function enterWorld(){state.sound.armed=true;$('#entranceAudio').disabled=false;$('#hudAudio').disabled=false;$('#hudMute').disabled=false;$('#entranceAudio').textContent='MUSIC OFF';const t=$('#worldTransition'),label=t.querySelector('strong'),steps=[['ground','GROUND LAYERS READY'],['assembly','BASE ASSEMBLY'],['core','ENERGY CORE ONLINE'],['camera','CAMERA APPROACH'],['hud','WORLD HUD READY']];t.classList.add('is-active');t.setAttribute('aria-hidden','false');if(effectiveEffect()==='static'){label.textContent='OPERATIONS ATLAS READY';sceneTimers.timeout(()=>showScene('world-map'),120);return}steps.forEach((item,index)=>sceneTimers.timeout(()=>{$('#entrance').dataset.entranceStage=item[0];label.textContent=item[1]},index*220));sceneTimers.timeout(()=>showScene('world-map'),1180)}
  function resetMissionPanel(){sceneTimers.cancelAll();const data=missionData[state.mission.id];state.mission.stage='idle';state.mission.playback='stopped';state.mission.approvedByMIS=false;$('#missionStep').textContent='READY';$('#missionStageTitle').textContent='準備進入任務';$('#missionDescription').textContent='場景將先呈現問題，再顯示 BLOCKOPS 如何協助，最後停在 MIS 人工決策。';$('#missionFacts').innerHTML='<li>所有資料皆為虛構展示</li><li>不連接正式設備</li><li>不執行任何真實 Action</li>';$('#missionResult').hidden=true;$('#missionStart').hidden=false;$('#missionStart').disabled=false;$('#missionPause').disabled=true;$('#missionPause').textContent='暫停';$('#missionApprove').hidden=true;$('#missionApprove').textContent=data.action;$('#missionReplay').hidden=true;$('#missionCompare').hidden=data.type!=='mask';$('#missionCompare').textContent='查看遮罩後';$('#mission').classList.remove('show-mask-after');$('#mission').dataset.stage='idle';$('#mission').classList.remove('is-paused');updateHud(state.selectedRegion)}
  function openRegion(region){const data=missionData[region];if(!data)return;state.selectedRegion=region;state.visitedRegions.add(region);state.mission={id:region,stage:'idle',playback:'stopped',approvedByMIS:false,actualAction:0};$(`.region[data-region="${region}"]`)?.classList.add('is-visited');$('#mission').dataset.mission=data.type;$('#mission').style.setProperty('--mission-color',data.theme);$('#missionCode').textContent=data.code;$('#missionTitle').textContent=data.title;resetMissionPanel();showScene('mission')}
  function renderMissionStage(index){const data=missionData[state.mission.id];const current=data.stages[index];if(!current)return;state.mission.stage=current[0];state.mission.playback=current[0]==='awaiting_mis'?'paused':'playing';$('#mission').dataset.stage=current[0];$('#missionStep').textContent=current[1];$('#missionStageTitle').textContent=current[2];$('#missionDescription').textContent=current[0]==='awaiting_mis'?'流程已安全停住。請由 MIS 執行畫面上的模擬確認後才會繼續。':'場景正在用純前端動畫呈現這一步，不會連接或操作任何正式系統。';$('#missionFacts').innerHTML=current[3].map(item=>`<li>${item}</li>`).join('');$('#missionPause').disabled=current[0]==='awaiting_mis';$('#missionApprove').hidden=current[0]!=='awaiting_mis';updateHud(state.selectedRegion);if(current[0]!=='awaiting_mis')sceneTimers.timeout(()=>renderMissionStage(index+1),effectiveEffect()==='static'?500:2200)}
  function startMission(){sceneTimers.cancelAll();state.mission.playback='playing';$('#missionStart').hidden=true;$('#missionPause').disabled=false;renderMissionStage(0)}
  function toggleMissionPause(){if(['idle','awaiting_mis','completed'].includes(state.mission.stage))return;if(state.mission.playback==='playing'){sceneTimers.cancelAll();state.mission.playback='paused';$('#missionPause').textContent='繼續';$('#mission').classList.add('is-paused')}else{state.mission.playback='playing';$('#missionPause').textContent='暫停';$('#mission').classList.remove('is-paused');const i=Math.max(0,missionData[state.mission.id].stages.findIndex(s=>s[0]===state.mission.stage));sceneTimers.timeout(()=>renderMissionStage(i+1),500)}}
  function approveMission(){if(state.mission.stage!=='awaiting_mis')return;state.mission.approvedByMIS=true;state.mission.stage='completed';state.mission.playback='stopped';$('#mission').dataset.stage='completed';$('#missionApprove').hidden=true;$('#missionPause').disabled=true;$('#missionResult').hidden=false;$('#missionReplay').hidden=false;$('#missionStep').textContent='DEMO COMPLETED';$('#missionStageTitle').textContent='模擬流程完成，世界恢復正常。';$('#missionDescription').textContent='這是畫面狀態示範；未傳送資料，也未操作真實設備。';$('#missionFacts').innerHTML='<li>simulate_only=true</li><li>Actual Action：0</li><li>最終控制權仍由 MIS 掌握</li>';updateHud(state.selectedRegion)}
  function renderTechnologyModules(){const host=$('.core-modules');host.innerHTML=technologyData.map((item,i)=>`<button type="button" style="--i:${i};--module:${['#35ddd0','#8a63f6','#45b8f3','#62c95a','#f6c84c'][i%5]}" data-tech="${i}"><span>${String(i+1).padStart(2,'0')}</span><strong>${item[0]}</strong><small>${item[1]}</small></button>`).join('');host.addEventListener('click',event=>{const b=event.target.closest('[data-tech]');if(!b)return;const item=technologyData[Number(b.dataset.tech)];$$('.core-modules button').forEach(n=>n.classList.toggle('is-selected',n===b));$('#coreStatus').textContent=item[1];$('#corePanelTitle').textContent=item[0];$('#corePurpose').textContent=item[2];$('#coreRole').textContent=item[3];$('#coreSafety').textContent=item[4];$('#corePanel').hidden=false;$('#corePanel').classList.add('is-open');$('#coreClose').focus()})}
  function closeCorePanel(){$('#corePanel').hidden=true;$('#corePanel').classList.remove('is-open');$('.core-modules .is-selected')?.focus()}
  function backToMap(){state.mission.playback='stopped';sceneTimers.cancelAll();showScene('world-map');if(state.selectedRegion)$(`.region[data-region="${state.selectedRegion}"]`)?.focus()}
  const textEntry=t=>t.closest?.('input,textarea,select,[contenteditable="true"]');
  const interactive=t=>t.closest?.('button,a[href],summary,[role="button"]');
  $('#enterWorld').addEventListener('click',enterWorld);$$('.region').forEach(b=>b.addEventListener('click',()=>openRegion(b.dataset.region)));$$('[data-shortcut]').forEach(b=>b.addEventListener('click',()=>openRegion(b.dataset.shortcut)));$$('[data-destination]').forEach(b=>b.addEventListener('click',()=>{state.selectedRegion=null;showScene(b.dataset.destination)}));$$('[data-back-map]').forEach(b=>b.addEventListener('click',backToMap));
  $('#missionStart').addEventListener('click',startMission);$('#missionPause').addEventListener('click',toggleMissionPause);$('#missionApprove').addEventListener('click',approveMission);$('#missionReplay').addEventListener('click',()=>{resetMissionPanel();startMission()});$('#missionCompare').addEventListener('click',()=>{const after=$('#mission').classList.toggle('show-mask-after');$('#missionCompare').textContent=after?'查看遮罩前':'查看遮罩後'});$('#coreClose').addEventListener('click',closeCorePanel);
  $$('#entranceEffects,#hudEffects').forEach(control=>control.addEventListener('change',e=>{state.effectPreference=e.target.value;storage.set('blockops:v3:effect-level',state.effectPreference);renderEnvironment()}));$('#entrancePhase').addEventListener('click',()=>{state.worldPhase=state.worldPhase==='day'?'night':'day';storage.set('blockops:v3:manual-phase',state.worldPhase);renderEnvironment()});
  const audio=$('#previewAudio'),audioButtons=$$('#entranceAudio,#hudAudio'),muteButton=$('#hudMute'),volumeControl=$('#hudVolume');volumeControl.value=String(Math.round(state.sound.volume*100));muteButton.setAttribute('aria-pressed',String(state.sound.muted));async function toggleAudio(){if(!state.sound.armed)return;if(!state.sound.initialized){audio.src='../assets/audio/local-preview/local-preview-bgm.mp3';audio.volume=state.sound.volume;audio.muted=state.sound.muted;state.sound.initialized=true}if(audio.paused){try{await audio.play();state.sound.enabled=true}catch(_){state.sound.enabled=false}}else{audio.pause();state.sound.enabled=false}audioButtons.forEach(button=>{button.textContent=state.sound.enabled?'MUSIC ON':'MUSIC OFF';button.setAttribute('aria-pressed',String(state.sound.enabled))})}audioButtons.forEach(button=>button.addEventListener('click',toggleAudio));muteButton.addEventListener('click',()=>{state.sound.muted=!state.sound.muted;audio.muted=state.sound.muted;storage.set('blockops:v3:audio-muted',String(state.sound.muted));muteButton.textContent=state.sound.muted?'UNMUTE':'MUTE';muteButton.setAttribute('aria-pressed',String(state.sound.muted))});volumeControl.addEventListener('input',()=>{state.sound.volume=Number(volumeControl.value)/100;audio.volume=state.sound.volume;storage.set('blockops:v3:audio-volume',String(state.sound.volume))});audio.addEventListener('error',()=>{state.sound.enabled=false;audioButtons.forEach(button=>{button.textContent='MUSIC UNAVAILABLE';button.setAttribute('aria-pressed','false')})},{once:true});
  $('#contactForm').addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget;if(!f.reportValidity()){$('#contactStatus').textContent='請先完成標示的展示欄位。';return}$('#contactStatus').textContent='展示完成，未傳送真實資料。';f.reset()});
  document.addEventListener('keydown',e=>{if(e.isComposing||e.metaKey||e.ctrlKey||e.altKey||textEntry(e.target))return;const key=e.key.toLowerCase();if(key==='m'){e.preventDefault();backToMap();return}if(e.key==='Escape'){if(!$('#corePanel').hidden)closeCorePanel();else if(state.currentScene!=='entrance')backToMap();return}if(e.key===' '&&state.currentScene==='mission'){if(interactive(e.target))return;e.preventDefault();toggleMissionPause();return}const n=Number(e.key);if(n>=1&&n<=6){e.preventDefault();openRegion(Object.keys(regionNames)[n-1])}});
  document.addEventListener('visibilitychange',()=>{if(document.hidden){state.mission.resumeAfterVisibility=state.currentScene==='mission'&&state.mission.playback==='playing';globalTimers.cancelAll();sceneTimers.cancelAll();clearTransition()}else{scheduleClock();if(state.mission.resumeAfterVisibility){state.mission.resumeAfterVisibility=false;const i=Math.max(0,missionData[state.mission.id].stages.findIndex(s=>s[0]===state.mission.stage));sceneTimers.timeout(()=>renderMissionStage(i+1),500)}}});reducedQuery.addEventListener?.('change',()=>{state.reducedMotion=reducedQuery.matches;sceneTimers.cancelAll();renderEnvironment();if(state.currentScene==='mission'&&state.mission.playback==='playing'){const i=Math.max(0,missionData[state.mission.id].stages.findIndex(s=>s[0]===state.mission.stage));sceneTimers.timeout(()=>renderMissionStage(i+1),effectiveEffect()==='static'?80:500)}});
  renderTechnologyModules();renderEnvironment();scheduleClock();updateHud();window.BLOCKOPS_V3_STATE=state;
})();
