import type { Solution } from '../types';
export const solutions: Solution[] = [
  { id:1,title:'Build a stable IT foundation',problem:'The environment, backups and recovery plans lack a shared baseline.',method:'Map assets and relationships, then identify breakpoints and priorities.',outcome:'An architecture map, risk list and phased improvement path.',fit:'Organizations preparing to replace, expand or reorganize existing infrastructure.' },
  { id:2,title:'Connect scattered systems',problem:'Sites, cloud, identities and suppliers operate separately.',method:'Establish service relationships, access boundaries and handoffs.',outcome:'A maintainable service blueprint with clear ownership.',fit:'Multi-site, multi-cloud or cross-supplier operating environments.' },
  { id:3,title:'Make security events clear',problem:'Monitoring, log and endpoint messages repeat without context.',method:'Correlate events by asset, service and time, then help prioritize.',outcome:'Readable event summaries and a consistent tracking path.',fit:'Teams with monitoring tools but excessive notifications and unclear priorities.' },
  { id:4,title:'Reduce repetitive operations',problem:'Routine work depends on personal habits and is hard to review.',method:'Turn steps, approvals and results into standard workflows.',outcome:'Controlled, traceable operations that can improve over time.',fit:'Environments with repetitive inspections, identity or maintenance work and inconsistent records.' },
  { id:5,title:'Support night and holiday duty',problem:'High notification volume makes impact hard to assess quickly.',method:'Summarize important events, context and suggested checks.',outcome:'Lower notification noise and clearer handoff information.',fit:'IT teams that need off-hours event context and clear human handoff.' },
  { id:6,title:'Keep critical actions human-led',problem:'Without approval, high-impact actions lack clear accountability.',method:'Stop at a pre-execution approval point and record target, reason and approval.',outcome:'A controlled decision path with a complete audit trail.',fit:'Environments that need automation while preserving approval and accountability.' },
  { id:7,title:'Turn experience into team knowledge',problem:'Decision context is scattered across messages and personal experience.',method:'Organize events, runbooks, decisions and outcomes.',outcome:'Searchable, reviewable knowledge that can be handed over.',fit:'Teams with concentrated knowledge, difficult handoffs or a need for shared operating practices.' }
];
